// TODO: date양식 맞추기
export const dummyTodosList = [
  // 8월 27일 토요일
  {
    id: 1,
    task: "풀리퀘 확인하기",
    date: "2022-08-27",
    isDone: true,
    timer: 30,
  },
  {
    id: 2,
    task: "Homework",
    date: "2022-08-27",
    isDone: true,
    timer: 25,
  },
  {
    id: 3,
    task: "Yoga Class",
    date: "2022-08-27",
    isDone: false,
    timer: 180,
  },
  // 8월 28일 일요일
  {
    id: 4,
    task: "풀리퀘 확인하기",
    date: "2022-08-28",
    isDone: true,
    timer: 30,
  },
  {
    id: 5,
    task: "과제",
    date: "2022-08-28",
    isDone: false,
    timer: 25,
  },
  {
    id: 6,
    task: "Yoga Class",
    date: "2022-08-28",
    isDone: true,
    timer: 180,
  },
  // 8월 29일 월요일
  {
    id: 7,
    task: "Bug groceries",
    date: "2022-08-29",
    isDone: true,
    timer: 30,
  },
  {
    id: 8,
    task: "60 mins plank",
    date: "2022-08-29",
    isDone: false,
    timer: 60,
  },
  {
    id: 9,
    task: "Take vitamins",
    date: "2022-08-29",
    isDone: true,
    timer: 0,
  },
  {
    id: 10,
    task: "Study Typescript",
    date: "2022-08-29",
    isDone: true,
    timer: 200,
  },
  {
    id: 11,
    task: "Learn Angular",
    date: "2022-08-29",
    isDone: true,
    timer: 90,
  },
  // 8월 30일 화요일
  {
    id: 12,
    task: "buy milk",
    date: "2022-08-30",
    isDone: true,
    timer: 5,
  },
  {
    id: 13,
    task: "buy bananas",
    date: "2022-08-30",
    isDone: false,
    timer: 60,
  },
  {
    id: 14,
    task: "tim horton's",
    date: "2022-08-30",
    isDone: true,
    timer: 0,
  },
  {
    id: 15,
    task: "Update project plan ",
    date: "2022-08-30",
    isDone: false,
    timer: 172,
  },
  {
    id: 16,
    task: "create a meeting agenda",
    date: "2022-08-29",
    isDone: true,
    timer: 0,
  },
];

export const dummyPinnedReceipts = [
  {
    id: 2,
    todos: [
      {
        id: 1,
        task: "create a meeting agenda",
        date: "2022-08-29",
        isDone: true,
        timer: 0,
      },
    ],
    pinned: true,
    famous_saying: "Eat food. Not too much, mostly plants.",
    createdAt: "2022-08-01",
    updatedAt: "2022-08-02",
  },
  {
    id: 16,
    todos: [
      {
        id: 2,
        task: "create a meeting agenda",
        date: "2022-08-29",
        isDone: true,
        timer: 0,
      },
      {
        id: 3,
        task: "Update project plan ",
        date: "2022-08-29",
        isDone: false,
        timer: 172,
      },
    ],
    pinned: true,
    famous_saying: "Good advice is something a man gives when he is too old to set a bad example.",
    createdAt: "2022-08-01",
    updatedAt: "",
  },
  {
    id: 17,
    todos: [
      {
        id: 4,
        task: "create a meeting agenda",
        date: "2022-08-30",
        isDone: true,
        timer: 0,
      },
      {
        id: 5,
        task: "Update project plan ",
        date: "2022-08-30",
        isDone: false,
        timer: 172,
      },
      {
        id: 6,
        task: "60 mins plank",
        date: "2022-08-30",
        isDone: false,
        timer: 60,
      },
      {
        id: 7,
        task: "Take vitamins",
        date: "2022-08-30",
        isDone: true,
        timer: 0,
      },
      {
        id: 10,
        task: "Study Typescript",
        date: "2022-08-30",
        isDone: true,
        timer: 200,
      },
      {
        id: 11,

        task: "Learn Angular",
        date: "2022-08-30",
        isDone: true,
        timer: 90,
      },
    ],
    pinned: true,
    famous_saying: "Respect your elders.",
    createdAt: "2022-08-01",
    updatedAt: "",
  },
  {
    id: 1,
    todos: [
      {
        id: 12,
        task: "60 mins plank",
        date: "2022-10-30",
        isDone: false,
        timer: 60,
      },
      {
        id: 13,
        task: "Take vitamins",
        date: "2022-10-30",
        isDone: true,
        timer: 0,
      },
      {
        id: 14,
        task: "Study Typescript",
        date: "2022-10-30",
        isDone: true,
        timer: 200,
      },
      {
        id: 15,
        task: "Learn Angular",
        date: "2022-10-30",
        isDone: true,
        timer: 90,
      },
    ],
    pinned: true,
    famous_saying: "Most things done in secrecy are better left undone.",
    createdAt: "2022-08-01",
    updatedAt: "",
  },
];
